server:
  port: 9993

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goddess?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 0
  application:
    name: crawler-goddess
  rabbitmq:
    host: www.iamcrawler.cn
    port: 5672
    username: liuliang
    password: liuliang

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9990/eureka/


init-db: true
#txmanager地址
tm:
  manager:
    url: http://localhost:6000/tx/manager/
logging:
  level:
    com:
      codingapi: info