


spring:
  application:
    name: crawler-goddess
  liquibase:
    change-log: classpath:liquibase\master.xml

mybatis:
  type-aliases-package: cn.iamcrawler.crawler_common.domain.goddess
  mapper-locations: cn/iamcrawler/crawlergoddess/mapper/*Mapper.xml
  type-handlers-package: cn.iamcrawler.crawlergoddess.mapper.typehandler
  global-config:
    refresh-mapper: true