server:
  port: 9993

spring:
  datasource:
    url: jdbc:mysql://www.iamcrawler.cn:3306/goddess?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver
  redis:
    host: www.iamcrawler.cn
    port: 6379
    password: 123456
    database: 0
  application:
    name: crawler-goddess
  rabbitmq:
    host: www.iamcrawler.cn
    port: 5672
    username: liuliang
    password: liuliang
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 47.106.77.78:9300
#      repositories:
#        enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9990/eureka/


init-db: true
#txmanager地址
tm:
  manager:
    url: http://localhost:6000/tx/manager/
logging:
  level:
    com:
      codingapi: info