liquibase:
  change-log: classpath:liquibase\master.xml


spring:
  application:
    name: crawler-goddess

mybatis:
  type-aliases-package: cn.iamcrawler.crawlergoddess.domain
  mapper-locations: cn/iamcrawler/crawlergoddess/mapper/xml/*Mapper.xml
  type-handlers-package: cn.iamcrawler.crawlergoddess.mapper.typehandler
  global-config:
    refresh-mapper: true